name: Terraform Plan and Apply on Main Branch Push
on:
 push:
   branches:
     - master

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    env:
      TF_VAR_SNOWFLAKE_REGION: ${{ secrets.SNOWFLAKE_REGION }}
      TF_VAR_SNOWFLAKE_ACCOUNT_NAME: ${{ secrets.SNOWFLAKE_ACCOUNT_NAME }}
      TF_VAR_SNOWFLAKE_ORGANIZATION_NAME: ${{ secrets.SNOWFLAKE_ORGANIZATION_NAME }}
      TF_VAR_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      TF_VAR_SNOWFLAKE_AUTHENTICATOR: ${{ secrets.SNOWFLAKE_AUTHENTICATOR }}
      TF_VAR_SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Show Environment Variables
        run: |
          echo "TF_VAR_SNOWFLAKE_REGION"
          echo "TF_VAR_SNOWFLAKE_ACCOUNT_NAME"
          echo "TF_VAR_SNOWFLAKE_ORGANIZATION_NAME"
          echo "TF_VAR_SNOWFLAKE_USER"
          echo "TF_VAR_SNOWFLAKE_AUTHENTICATOR"
          echo "TF_VAR_SNOWFLAKE_PRIVATE_KEY"

      - name: Terraform Initialize
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
